language: ruby
cache: bundler
rvm:
- 2.4.1
addons:
  postgresql: '9.6'
  sources:
  - google-chrome
  apt:
    packages:
    - google-chrome-stable
services:
- redis-server
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get install libnss3
- sudo apt-get --only-upgrade install google-chrome-stable
- sudo cp chromedriver /usr/local/bin/.
- sudo chmod +x /usr/local/bin/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails db:test:prepare
- bundle exec rails test
- bundle exec rails test:system
deploy:
  matrix:
  - provider: heroku
    app: hurricane-florence-api
    on:
      tags: true 
    run:
    - rails db:migrate
    - rake cleanup
  api_key:
    secure: hrf+0+plUYp1LH+yRFlDql2yi6qzUmPlIsRzUSPfkYKgiOoTTRqi5wKsGXHMBEZSoTmdPlkIwyNdv4tCIgegatlY8xB+++OOcyy1GQGEEk0Iqjji1EBh4IYdBXyK6QOiXbGXnll8GSua6DUlRN4om/L0oG1STaqHt1zbpnicawrRIrpzvytCVOdcIAfJlsq/S9zwL0cK7hQvx2dhSZO9O3Qx5MXiYJuAD4Ve1ggIao9HRUs9Ijsdu+AsEDPPOLMJ2ZliGeWm5VxaXh+gtB3QLObFIpa1j4gzOUbNSLZDefcSGKkcg5lAx7ZG+/aUFdeE0Zhu8UrJHg4zQzac4eZXducjQgxyDWAnG5leu/SShv64PG+f9z+YioUQTqyGXxMC5tFz9vTO+6iq1iriHorGf4AeW4+Kv9wJJ5lzvR3AfjmdyXHhC1mI2St/IL+4wlVd30t2pO3CypucF2sPWtBNr3jN18XTHQyob/vvwrHsXS+2a4buZUxFvooBpabpXxAgczUHyZATudE6MgWxhY+OTjGbOYXZFcA1lyqFpseNrexYrkhzTPpy3mmN3U/aKFb6pngFUCf1cxuJUihuCtEA4b36sABpWsUtMyFQF0azVAt9XRdz7D2KdFgo6l7G6J3vfo2JwJiKTGQFh69xWuKwQ2qnWktpEn8bZW8jnZADG9o=
